#cloud-config
users:
  - name: saho
    groups: [sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: $6$rounds=4096$UWXEUsdlup8Lf/cm$nhrniSxvTaJJGaEJ/HxA2x7KRdFpSozT5YWMSudCXtJYosgoHzlD.ZozstFl/4Ev9Pih7rQAuh6R7wiOe2nQK0
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFKAKsgtn42Qz+ZwtIGGcqWMewTSl9DSUCthFl2yB/4k79qm7eYpZtW8TByXi5S46H0aJjYlxdcpleVtZIecbE6r5MYM6EzuQCN7oQLPz1SqQTvFwudbr+5ayOhYoS1vzHJVyp0Kz5X7JuqCTYClJL9Kn9bIwXmYpomgKo3MwjtcfXhx6Opxn3xO3lGfFrEORNd438AhQ+aD6lNgLqwgM6zyjuqsnnc/AjQV/nvAn+wupgAw76OvN9UWZWQYiP8QgVxCb9y7b/K8IYsO2xrmfxL4w0+qFRz7SnCQmxhvQ2EHiCir2iEOiyQElOyqunEYz4r5ZSlcYoEEsLUl+5bue6RXVboSfarDR26ucWIWua+n4Hz0j8lqw6ckJWdtmklU5+21VYWwa8DLbUvvD0AXU+MHBI14DM2JE5kgh62N021EIBHUdeqceIlltCCpIXrYySynvdKVLnNgyfjOifc5nPAKfh6guYGiWdLENJXCf/FB2Qa1aHFloTuLs1tD3a0f8= saho@DESKTOP-O12DSBC
package_upgrade: true
package_reboot_if_required: true
locale: fi_FI.utf8
timezone: Europe/Helsinki
runcmd:
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik" sh -
  - mkdir /home/saho/.kube && cp /etc/rancher/k3s/k3s.yaml /home/saho/.kube/config && chown saho /home/saho/.kube/config
