apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: https://github.com/SamiHonkasalo/hcloud.git
      path: charts/portfolio
      helm:
        valueFiles:
          - $values/applications/portfolio/values.yaml
    - repoURL: https://github.com/SamiHonkasalo/hcloud.git
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: portfolio
  ignoreDifferences:
  - group: apps
    kind: ServiceAccount
    jqPathExpressions:
    - .metadata.automountServiceAccountToken
