server:
  ingress:
    enabled: true
    ingressClassName: nginx
    https: false
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argocd.k3s.saho.dev
    tls:
      - secretName: argocd-ingress-tls
        hosts:
          - argocd.k3s.saho.dev
  ingressGrpc:
    enabled: true
    ingressClassName: nginx
    https: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    hosts:
      - grpc.argocd.k3s.saho.dev
    tls:
      - secretName: argocd-ingress-grpc-tls
        hosts:
          - grpc.argocd.k3s.saho.dev

configs:
  cm:
    admin.enabled: false
