server:
  ingress:
    enabled: true
    hosts:
    - argocd.k3s.saho.dev
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.k3s.saho.dev

configs:
  params:
    "server.insecure": true
