apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: argocd
  name: argocd-tls
spec:
  commonName: argocd.k3s.saho.dev
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "argocd.k3s.saho.dev"
