server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    ingressClassName: traefik
    hosts:
      - argocd.95.216.155.80.nip.io
      - argocd.k3s.saho.dev
    tls:
      - secretName: argocd-tls
        hosts:          
          - argocd.k3s.saho.dev

configs:
  params:
    "server.insecure": true
