ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  ingressClassName: traefik
  hosts:
    - host: whoami.k3s.saho.dev
      paths:
        - /
  tls:
    - secretName: whoami-tls
      hosts:
        - whoami.k3s.saho.dev
