apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: https://cowboysysop.github.io/charts/
      chart: whoami
      targetRevision: 5.1.0
      helm:
        valueFiles:
          - $values/applications/whoami/values.yaml
    - repoURL: https://github.com/SamiHonkasalo/hcloud.git
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: whoami
